import './globals.css';
import StoryblokProvider from '@/components/StoryblokProvider';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const viewport = {
	width: 'device-width',
	initialScale: 1,
}

export default function RootLayout({ children }) {
	return (
		<StoryblokProvider>
			<html lang="en" style={{ margin: 0, padding: 0, width: '100%' }} suppressHydrationWarning>
				<body style={{
					margin: 0,
					padding: 0,
					width: '100%',
					maxWidth: 'none',
					overflowX: 'hidden',
				}} suppressHydrationWarning>
					<main style={{
						display: 'block',
						padding: 0,
						margin: 0,
						maxWidth: 'none',
						width: '100%',
					}}>
						{children}
					</main>
				</body>
			</html>
		</StoryblokProvider>
	);
}
