import './globals.css';
import StoryblokProvider from '@/components/StoryblokProvider';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<StoryblokProvider>
			<html lang="en">
				<body style={{ margin: 0, padding: 0, width: '100%', overflowX: 'hidden' }}>
					{children}
				</body>
			</html>
		</StoryblokProvider>
	);
}
